### ISSUE TITLE
Grd.scss

### ISSUE THREAD

**Issue by tnViking** [1000ch/grd#12]
I didn't feel like creating a whole separate project for it, so I just add it here.
Some people, like me, prefer using SCSS to handle grid creation, so I took your code and applied it to sass.
```scss
@mixin grid($align: stretch, $justify: left) {
	@if $align == 'top'			{ $align: flex-start; }
	@if $align == 'middle'		{ $align: center; }
	@if $align == 'bottom'		{ $align: flex-end; }
	@if $align == 'stretch'		{ $align: stretch; }
	@if $align == 'baseline'	{ $align: baseline; }

	@if $justify == 'left'		{ $justify: flex-start; }
	@if $justify == 'center'	{ $justify: center; }
	@if $justify == 'right'		{ $justify: flex-end; }
	@if $justify == 'between'	{ $justify: space-between; }
	@if $justify == 'around'	{ $justify: space-around; }

	align-items: $align;
	display: flex;
	flex-wrap: wrap;
	justify-content: $justify;
}

@mixin cell($x: fill, $n: 12) {
	@if $x == 'fill' {
		flex-grow: 1;
		min-width: 0;
		width: 0;
	} @else {
		flex-grow: 0;
		width: calc(100% * (#{$x} / #{$n}));
	}

	box-sizing: border-box;
	flex-shrink: 0;
}
```

Dead easy to use.
**grid()** will default to default flex, so stretch and flex-start.
**cell()** will default to fill

Usage:
First parameter of **cell()** is the align-items position, will default to _stretch_, the second parameter of **cell()** is the justify-content, and it will default to _flex-start_

First parameter of **cell()** is where you specify it's width, it will default to auto fill it's width, the second parameter of **cell()** is how many "columns" there are, and will default to _12_

**Comment by tnViking** [comment]
Example usage:
```scss
main { @include grid(middle, between); }
main article { @include cell(); }
main aside { @include cell(3); }
```

which would output
```css
main {
  align-items: center;
  display: flex;
  flex-wrap: wrap;
  justify-content: space-between;
}

main article {
  flex-grow: 1;
  min-width: 0;
  width: 0;
  box-sizing: border-box;
  flex-shrink: 0;
}

main aside {
  flex-grow: 0;
  width: calc(100% * (3 / 12));
  box-sizing: border-box;
  flex-shrink: 0;
}
```
