### ISSUE TITLE
Sass,pls

### ISSUE THREAD

**Issue by aolko** [1000ch/grd#9]
'cos thr shld be a vrsn w/o smntc trsh

**Comment by 1000ch** [comment]
Give me a clear sentence?

**Comment by aolko** [comment]
Anyway, please make a sass versio w/o a semantic trash like you currently have now (define grid in-styles not in html)

**Comment by megaghz** [comment]
grid is just style. Applied as classes.

**Comment by aolko** [comment]
here's what i mean 
![wow](http://i.imgur.com/BidTsmx.png)

**Comment by willdavidow** [comment]
Or you could ask nicely, and then submit a pull request.. Just an idea...

**Comment by SiamKreative** [comment]
I would also love the ability to use this grid with SASS.

**Comment by bfred-it** [comment]
Not sure I follow.

You want to do this:

```scss
.example {
    @include wrap;
    &__item {
        @include col;
        @include col(1,3);
    }
}
```

Instead of just doing:

```scss
.example {
    display: flex;
    flex-wrap: wrap;
    &__item {
        flex-shrink: 0;
        width: calc(100% * 1 / 12); 
    }
}
```

It makes no sense. The point of this is to provide classes ready to use on HTML. Each rule is a single property: https://github.com/1000ch/grd/blob/gh-pages/src/grd.css
